### ISSUE TITLE
Attempting to run container fails with docker not found

### ISSUE THREAD

**Issue by ddelnano** [wernight/docker-mopidy#1]
I tried to run your sample command with my spotify and soundcloud credentials and I get an error in the [entrypoint.sh](https://github.com/wernight/docker-mopidy/blob/master/entrypoint.sh#L9) file on line 9 saying docker not found.  So I think it seems to be running the docker run command that I used to try and run the container.

So I am wondering why the entrypoint.sh file has `exec "$@"`, I see previously it was the mopidy command.

**Comment by wernight** [comment]
What was the command you ran?

**Comment by ddelnano** [comment]
I used

```bash
docker run -d \
      -e PULSE_SERVER=tcp:$(hostname -i):4713 \
      -e PULSE_COOKIE_DATA=$(pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*') \
      -v $PWD/media:/var/lib/mopidy/media:ro \
      -v $PWD/local:/var/lib/mopidy/local \
      -p 6600:6600 -p 6680:6680 \
      wernight/mopidy \
      -o spotify/username=USERNAME -o spotify/password=PASSWORD \
      -o gmusic/enabled=false \
      -o soundcloud/enabled=false
```

**Comment by wernight** [comment]
Sorry the example was wrong as it's missing `mopidy` after `wernight/mopidy` (part of a recent change). I updated the README.

**Comment by ddelnano** [comment]
Ok cool.  I'll try it later and if it works I will close the issue.
