### ISSUE TITLE
Problems with running docker-mopidy

### ISSUE THREAD

**Issue by gabrielaigner** [wernight/docker-mopidy#29]
So I started with running the docker command: (I want use mopidy to stream Spotify)
```
docker run -dit \
> wernight/mopidy \
> mopidy \
> -o spotify/username=MyUsername -o spotify/password=MyPassword
```
Then it loaded the image, and ran the container.

Unfortunately, every time I run the container in `detached` `-d` like above, it automatically stops immediately.

When I run it without `detached`  just with `-it` It throws the error:
```
/bin/bash: /entrypoint.sh: Permission denied
```

Does anyone of you know why this keeps happening?
Do I need to configure something or did I miss something? Thanks

**Comment by wernight** [comment]
I don't think you can run `-it` with `-d`. That doesn't make sense as there are no inputs. However that's not what the error says.
