### ISSUE TITLE
Error parsing reference: ":4713" is not a valid repository/tag.

### ISSUE THREAD

**Issue by budkin** [wernight/docker-mopidy#6]
Hi, I'm a docker newbie, I get this error message, when I try to run

```
$ docker run -d \
      -e PULSE_SERVER=tcp:$(hostname -i):4713 \
      -e PULSE_COOKIE_DATA=$(pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*') \
      -v $PWD/media:/var/lib/mopidy/media:ro \
      -v $PWD/local:/var/lib/mopidy/local \
      -p 6600:6600 -p 6680:6680 \
      wernight/mopidy \
      mopidy \
      -o spotify/username=USERNAME -o spotify/password=PASSWORD \
      -o gmusic/username=USERNAME -o gmusic/password=PASSWORD \
      -o soundcloud/auth_token=TOKEN
```

**Comment by wernight** [comment]
What's the error?

**Comment by geripgeri** [comment]
@budkin It's because you have to add ' symbol (Currently it's parsed as key:value) 

```
-e PULSE_SERVER='tcp:$(hostname -i):4713' \
```

@wernight  I think you should update the Readme and also the Dockerhub Readme.

**Comment by wernight** [comment]
Thanks, I'm using ZSH and this only shows on Bash.

**Comment by budkin** [comment]
I was using zsh as well, I solved this issue by invoking docker with `net --host` and `-e PULSE_SERVER=tcp:127.0.0.1:4713` options

**Comment by wernight** [comment]
I've updated the readme so it should be fixed now.
